spring.application.name=multi-models
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.ollama.chat.model=llama3.2:1b
# To say the Framework: "Don't create any kind of
# ChatClient Builder or ChatClient Beans. I'm going to
# create everything by myself"
spring.ai.chat.client.enabled=false
